homeassistant:
  name: Home
  latitude: 40.658939
  longitude: -74.39030385
  elevation: 52
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
logger:
  default: error
frontend:
history:
discovery:
sun:
logbook:
#updater:
  #reporting: true
recorder:
  # Delete events and states older than 2 weeks
  purge_days: 14
  db_url: !secret db_url

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
zone: !include zones.yaml
group: !include groups.yaml
sensor: !include devices/sensors.yaml
camera: !include devices/cameras.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
automation: !include automation.yaml
input_boolean: !include input_boolean.yaml
switch: !include switches.yaml
#
#
# ecobee Thermostat
#
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: False
#
# Wink API
#
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret
#
# Hue API
#
light:
  platform: hue
  host: 192.168.1.151
  allow_unreachable: true
  filename: phue.conf
#
# IFTTT API
#
ifttt:
  key: !secret ifttt_key
#
# Nest API
#
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#
# ZWave Configs
#
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000
  customize:
    binary_sensor.aeotec_multisensor_6_sensor_7_0:
        polling_intensity: 1
    binary_sensor.aeotec_multisensor_6_sensor_8_0:
        polling_intensity: 1
#
# TTS Settings
#
tts:
  - platform: google
    language: 'en-uk'

#
# Media Players
#
media_player:
  platform: plex
#
media_player 2:
  platform: cast
#  host: 192.168.1.158
#
#media_player 3:
#  platform: cast
#  host: 192.168.1.157
#
media_player 3:
  platform: firetv
#
# Presence Detection/Location
#
device_tracker:
  - platform: nmap_tracker
    hosts: 192.168.1.1/24
    home_interval: 5
  - platform: owntracks
    max_gps_accuracy: 100
  - platform: automatic
    client_id: !secret automatic_client_id
    secret: !secret automatic_secret
    username: !secret automatic_user
    password: !secret automatic_PW

proximity:
  home:
    ignored_zones:
      - NPS
    devices:
      - device_tracker.rpitera_rpitera
      - device_tracker.ford_fusion
    tolerance: 16

#
# MQTT Broker - CloudMQTT
#
mqtt:
  broker: m12.cloudmqtt.com
  port: 17070
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password
#
# Notification
#
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: ecobee
    name: ecobee
  - platform: html5
    name: HTML5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
#
#
#  Alarm Control Panel
#
#
alarm_control_panel:
  platform: manual
  name: "HA Alarm"
  code: !secret alarm_code
  pending_time: 60
  trigger_time: 60
#
#
#  Shell Commands
#
shell_command:
  backup_configs: 'sudo tar -zcvf homeassistant_backup.gz $( find -name "*.yaml" )'
#
#
# Alexa Integration
#
alexa:
  intents:
    ActivateSceneIntent:
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml
      action:
        service: scene.turn_on
        data_template:
          entity_id: scene.{{ Scene | replace(" ", "_") }}

    QueryLockIntent:
      speech:
        type: plaintext
        text: >
          {% if is_state('lock.front_door', 'locked') %}
            the door is locked Robert
          {% else %}
            the door is unlocked Robert
          {% endif %}



#
#   Statistical Sensors
#
#
binary_sensor:
  platform: trend
  entity_namespace: wx
  sensors:
    temperature_up:
      friendly_name: 'Apparent Temp Rising'
      entity_id: sensor.pws_feelslike_f
      sensor_class: heat
    temperature_down:
      friendly_name: 'Apparent Temp Falling'
      entity_id: sensor.pws_feelslike_f
      sensor_class: cold
      invert: Yes
    pressure_up:
      friendly_name: 'Barometric Pressure Rising'
      entity_id: sensor.pws_pressure_in
    pressure_down:
      friendly_name: 'Barometric Pressure Falling'
      entity_id: sensor.pws_pressure_in
      invert: Yes
    humidity_up:
      friendly_name: 'Relative Humidity Rising'
      entity_id: sensor.dark_sky_humidity
    humidity_down:
      friendly_name: 'Relative Humidity Falling'
      entity_id: sensor.dark_sky_humidity
      invert: Yes
    wind_speed_up:
      friendly_name: 'Sustained Wind Speed Increasing'
      entity_id: sensor.pws_wind_mph
    wind_speed_down:
      friendly_name: 'Sustained Wind Speed Decreasing'
      entity_id: sensor.pws_wind_mph
      invert: Yes
    precip_up:
      friendly_name: 'Probability of Precip Increasing'
      entity_id: sensor.dark_sky_precip_probability
    precip_down:
      friendly_name: 'Probability of Precip Decreasing'
      entity_id: sensor.dark_sky_precip_probability
      invert: Yes

#
#
# Google Calendar Integration
#
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#
#
# Harmony Hub Integration
#

remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.172
  