####################################################
#                                                  #
#                   Base Config                    #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 52
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  ssl_certificate: !secret http_ssl_certificate
  ssl_key: !secret http_ssl_key
  base_url: !secret http_base_url

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
logger:
  default: error
  logs:
    homeassistant.components.media_player.firetv: fatal
    homeassistant.components.media_player.cast: fatal
    homeassistant.components.cameras: fatal
    homeassistant.components.wink: critical
    homeassistant.components.sensor.darksky: info
frontend:
history:
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
discovery:
sun:
logbook:
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
updater:
  reporting: false
recorder:
  # Delete events and states older than 1 weeks
  purge_days: 7
  db_url: !secret db_url
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
config:

####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
zone: !include zones.yaml
group: !include groups.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
camera: !include devices/cameras.yaml
script: !include_dir_named scripts
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
input_boolean: !include devices/input_booleans.yaml
shell_command: !include shell_commands.yaml
input_select: !include devices/input_selects.yaml
media_player: !include devices/media_players.yaml
device_tracker: !include device_trackers.yaml
####################################################
#                                                  #
#                Platforms and APIs                #
#                                                  #
####################################################
#
#
# ecobee API
#
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: False
#
# Wink API
#
wink:
  email: !secret wink_email
  password: !secret wink_password
  client_id: !secret wink_client_id
  client_secret: !secret wink_client_secret
#
# Hue API
#
light:
  platform: hue
  host: 192.168.1.151
  scan_interval: 10
  allow_unreachable: true
  filename: phue.conf
#
# IFTTT API
#
ifttt:
  key: !secret ifttt_key
#
# Nest API
#
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#
# ZWave Configs
#
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml
  
  #Removed for update to 0.40.x
  #customize:
  #  binary_sensor.aeotec_multisensor_6_sensor_7_0:
  #      polling_intensity: 1
  #  binary_sensor.aeotec_multisensor_6_sensor_8_0:
  #      polling_intensity: 1


#
# Proximity
#

proximity:
  home:
    devices:
      - device_tracker.rpitera_rpitera
      - device_tracker.ford_fusion
    tolerance: 16

#
# MQTT Broker - CloudMQTT
#
mqtt:
  broker: m12.cloudmqtt.com
  port: 17070
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

#
# Notification
#
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: ecobee
    name: ecobee
  - platform: html5
    name: HTML5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: kodi
    name: kodi
    host: http://192.168.1.248
#
# TTS Settings
#
tts:
  - platform: google
    language: 'en-uk'

#
#
#  Alarm Control Panel
#
#
alarm_control_panel:
  platform: manual
  name: "HA Alarm"
  code: !secret alarm_code
  pending_time: 60
  trigger_time: 60

####################################################
#                                                  #
#             Platform Integrations                #
#                                                  #
####################################################
#
#
# Alexa Integration
#
alexa:
  intents:
    ActivateSceneIntent:
      speech:
        type: plaintext
        text: !include alexa_confirm.yaml
      action:
        service: scene.turn_on
        data_template:
          entity_id: scene.{{ Scene | replace(" ", "_") }}

    QueryLockIntent:
      speech:
        type: plaintext
        text: >
          {% if is_state('lock.front_door', 'locked') %}
            the door is locked Robert
          {% else %}
            the door is unlocked Robert
          {% endif %}


#
#
# Google Calendar Integration
#
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#
#
# Harmony Hub Integration
#
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.172

#
#
# Configurator Integration
#
panel_iframe:
  configurator:
    title: Editor
    icon: mdi:wrench
    url: https://westofeast.no-ip.org:3218

#
#
# Web Links for admin
#
weblink:
  entities:
    - name: Webmin
      url: https://westofeast.no-ip.org:10000
      icon: mdi:settings-box
    - name: Router
      url: http://192.168.1.1/
      icon: mdi:router-wireless
    - name: phpMyAdmin
      url: http://192.168.1.181/phpmyadmin
      icon: mdi:database
    - name: Kodi Interface
      url: http://192.168.1.248:8080
      icon: mdi:kodi
    - name: Plex Interface
      url: http://plex.tv
      icon: mdi:plex

#
#
# FFMPEG Integration
#
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg


#
#
# Input Slider for Internet Radio
#
input_slider:
  volume_radio:
    name: Volume
    icon: mdi:volume-high
    min: 0
    max: 1
    step: 0.05