####################################################
#                                                  #
#                   Base Config                    #
#                                                  #
####################################################
homeassistant:
  name: Home
  latitude: !secret lat
  longitude: !secret long
  elevation: 52
  unit_system: imperial
  time_zone: America/New_York
  customize: !include customize.yaml

http:
  api_password: !secret http_password
  #ssl_certificate: !secret http_ssl_certificate
  #ssl_key: !secret http_ssl_key
  #base_url: !secret http_base_url

####################################################
#                                                  #
#                     Enables                      #
#                                                  #
####################################################
logger:
  default: error
  logs:
    homeassistant.components.media_player.cast: fatal
    homeassistant.components.cameras: critical
    homeassistant.components.wink: critical
    homeassistant.components.octoprint: critical
    
frontend:
  themes:
    stealth:
      primary-color: black
    minimal:
      dark-primary-color: "#192231"
      primary-color: "#98878f"
      light-primary-color: "#98878f"
      paper-toggle-button-checked-ink-color: "#494e6b"
      paper-toggle-button-checked-button-color: "#494e6b"
      paper-toggle-button-checked-bar-color: "#494e6b"
      paper-slider-knob-color: "#494e6b"
      paper-slider-knob-start-color: "#494e6b"
      paper-slider-pin-color: "#494e6b"
      paper-slider-active-color: "#494e6b"
    
history:
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
     - sensor.dark_sky_apparent_temperature
     - sensor.dark_sky_cloud_coverage
     - sensor.dark_sky_dew_point
     - sensor.dark_sky_humidity
     - sensor.dark_sky_icon
     - sensor.dark_sky_nearest_storm_distance
     - sensor.dark_sky_ozone
     - sensor.dark_sky_precip
     - sensor.dark_sky_precip_intensity
     - sensor.dark_sky_precip_probability
     - sensor.dark_sky_pressure
     - sensor.dark_sky_summary
     - sensor.dark_sky_temperature
     - sensor.dark_sky_visibility
     - sensor.dark_sky_wind_bearing
     - sensor.dark_sky_wind_speed
     - sensor.dayofyear
     - sensor.moon
     - sensor.nextsunrise
     - sensor.nextsunset
     - sensor.ewr_travel_time
     - sensor.garwood_travel_time
     - sensor.westfield_travel_time
     - sensor.bound_brook_travel_time
     - sensor.bridgewater_area_travel_time
     - sensor.sandy_hook_travel_time
     - sensor.wilson_borough_travel_time
     - sensor.poconos_travel_time
     - sensor.pws_alerts
     - sensor.pws_dewpoint_string
     - sensor.pws_feelslike_string
     - sensor.pws_heat_index_string
     - sensor.pws_precip_today_string
     - sensor.pws_wind_string
     - sensor.pws_weather_1d
     - sensor.pws_weather_1h
     - sensor.pws_weather_1n
     - sensor.pws_weather_2d
     - sensor.pws_weather_2n
     - sensor.pws_weather_3d
     - sensor.pws_weather_3n
     - sensor.pws_weather_4d
     - sensor.pws_weather_4n
     - sensor.pws_weather_6h
     - sensor.pws_location
     - sensor.pws_observation_time
     - sensor.pws_station_id
     - sensor.since_last_boot
     - sensor.weekofyear
     - sun.sun
     - weblink.kodi_interface
     - weblink.octoprint
     - weblink.phpmyadmin
     - weblink.plex_interface
     - weblink.router
     - weblink.webmin



discovery:
sun:
logbook:
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date
     - sensor.dark_sky_apparent_temperature
     - sensor.dark_sky_cloud_coverage
     - sensor.dark_sky_dew_point
     - sensor.dark_sky_humidity
     - sensor.dark_sky_icon
     - sensor.dark_sky_nearest_storm_distance
     - sensor.dark_sky_ozone
     - sensor.dark_sky_precip
     - sensor.dark_sky_precip_intensity
     - sensor.dark_sky_precip_probability
     - sensor.dark_sky_pressure
     - sensor.dark_sky_summary
     - sensor.dark_sky_temperature
     - sensor.dark_sky_visibility
     - sensor.dark_sky_wind_bearing
     - sensor.dark_sky_wind_speed
     - sensor.dayofyear
     - sensor.moon
     - sensor.nextsunrise
     - sensor.nextsunset
     - sensor.ewr_travel_time
     - sensor.garwood_travel_time
     - sensor.westfield_travel_time
     - sensor.bound_brook_travel_time
     - sensor.bridgewater_area_travel_time
     - sensor.sandy_hook_travel_time
     - sensor.wilson_borough_travel_time
     - sensor.poconos_travel_time
     - sensor.pws_alerts
     - sensor.pws_dewpoint_string
     - sensor.pws_feelslike_string
     - sensor.pws_heat_index_string
     - sensor.pws_precip_today_string
     - sensor.pws_wind_string
     - sensor.pws_weather_1d
     - sensor.pws_weather_1h
     - sensor.pws_weather_1n
     - sensor.pws_weather_2d
     - sensor.pws_weather_2n
     - sensor.pws_weather_3d
     - sensor.pws_weather_3n
     - sensor.pws_weather_4d
     - sensor.pws_weather_4n
     - sensor.pws_weather_6h
     - sensor.pws_location
     - sensor.pws_observation_time
     - sensor.pws_station_id
     - sensor.since_last_boot
     - sensor.weekofyear
     - sun.sun
     - weblink.kodi_interface
     - weblink.octoprint
     - weblink.phpmyadmin
     - weblink.plex_interface
     - weblink.router
     - weblink.webmin

updater:
  reporting: false

recorder:
  # Delete events and states older than 1 week
  purge_days: 7
  db_url: !secret db_url
  include:
    domains:
      - alarm_control_panel
      - automation
      - binary_sensor
      - climate
      - lock
      - sensor
      - switch
      - media_player
  exclude:
    entities:
     - sensor.last_boot
     - sensor.date

config:


####################################################
#                                                  #
#                     Includes                     #
#                                                  #
####################################################
zone: !include zones.yaml
group: !include groups.yaml
sensor: !include devices/sensors.yaml
binary_sensor: !include devices/binary_sensors.yaml
camera: !include devices/cameras.yaml
shell_command: !include shell_commands.yaml
script: !include_dir_named scripts
scene: !include_dir_merge_list scenes
automation: !include_dir_merge_list automations
input_boolean: !include devices/input_booleans.yaml
input_select: !include devices/input_selects.yaml
input_slider: !include devices/input_sliders.yaml
media_player: !include devices/media_players.yaml
device_tracker: !include device_trackers.yaml

####################################################
#                                                  #
#                Platforms and APIs                #
#                                                  #
####################################################
#
#
# ecobee API
#
ecobee:
  api_key: !secret ecobee_api_key
  hold_temp: False

#
# Wink API
#
# wink:
#   local_control: True
  # email: !secret wink_email
  # password: !secret wink_password
  # client_id: !secret wink_client_id
  # client_secret: !secret wink_client_secret

#
# Hue API
#
light:
  platform: hue
  host: 192.168.1.221
  scan_interval: 10
  allow_unreachable: true
  filename: phue.conf

#
# IFTTT API
#
ifttt:
  key: !secret ifttt_key

#
# Nest API
#
nest:
  client_id: !secret nest_client_id
  client_secret: !secret nest_client_secret

#
# Ring API
#
ring:
  username: !secret ring_username
  password: !secret ring_password

#
# ZWave Configs
#
zwave:
  usb_path: /dev/ttyACM0
  config_path: /srv/hass/hass_venv/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-linux-armv7l.egg/config
  polling_interval: 60000
  device_config: !include zwave_device_config.yaml
  new_entity_ids: false
  

#
# Proximity
#
proximity:
  home:
    devices:
      - device_tracker.rpitera_rpitera
      - device_tracker.ford_fusion
    tolerance: 16

#
# MQTT Broker - CloudMQTT
#
mqtt:
  broker: m12.cloudmqtt.com
  port: 17070
  username: !secret cloudmqtt_username
  password: !secret cloudmqtt_password

#
# Notification
#
notify:
  - platform: pushbullet
    api_key: !secret pushbullet_key
    name: pushbullet
  - platform: ecobee
    name: ecobee
  - platform: html5
    name: HTML5
    gcm_api_key: !secret gcm_api_key
    gcm_sender_id: !secret gcm_sender_id
  - platform: kodi
    name: kodi
    host: http://192.168.1.248

#
# TTS Settings
#
tts:
  - platform: google
    language: 'en-uk'
    cache: false

#
#
#  Alarm Control Panel
#
#
alarm_control_panel:
  platform: manual
  name: "HA Alarm"
  code: !secret alarm_code
  pending_time: 60
  trigger_time: 60

####################################################
#                                                  #
#             Platform Integrations                #
#                                                  #
####################################################
#
#
# Alexa Integration
#
alexa:

intent_script:
  ActivateSceneIntent:
    speech:
      type: plain
      text: !include alexa_confirm.yaml
    action:
      service: scene.turn_on
      data_template:
        entity_id: scene.{{ Scene | replace(" ", "_") }}

  QueryLockIntent:
    speech:
      type: plain
      text: >
        {% if is_state('lock.front_door', 'locked') %}
          the door is locked Robert
        {% else %}
          the door is unlocked Robert
        {% endif %}

  SecureHouseIntent:
    action:
      event: SECURE
      event_data:
        type: secure
    speech:
      type: plain
      text: ""
  
  QueryHouseIntent:
    action:
      event: SECURE
      event_data:
        type: query        
    speech:
      type: plain
      text: ""


#
#
# Google Calendar Integration
#
google:
  client_id: !secret google_client_id
  client_secret: !secret google_client_secret

#
#
# Harmony Hub Integration
#
remote:
  - platform: harmony
    name: Living Room
    host: 192.168.1.172

  - platform: harmony
    name: Bedroom
    host: 192.168.1.214

#
#
# Configurator Integration
#
panel_iframe:
  configurator:
    title: Editor
    icon: mdi:wrench
    url: https://westofeast.no-ip.org:3218


#
#
# Anroid IP Webcam Integration
#
android_ip_webcam:
  - host: 192.168.1.212
    name: PrinterCam
    scan_interval: 10
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording
 
  - host: 192.168.1.217
    name: second floor
    scan_interval: 10
    sensors:
      - audio_connections
      - battery_level
      - battery_temp
      - battery_voltage
      - light
      - motion
      - pressure
    switches:
      - exposure_lock
      - ffc
      - focus
      - gps_active
      - night_vision
      - overlay
      - torch
      - whitebalance_lock
      - video_recording


#
#
# OctoPrint Integration
#
octoprint:
  host: 192.168.1.170:5000
  api_key: !secret octoprint_api_key
  
#
#
# Web Links for admin
#
weblink:
  entities:
    - name: Webmin
      url: https://westofeast.no-ip.org:10000
      icon: mdi:settings-box
    - name: Router
      url: http://192.168.1.1/
      icon: mdi:router-wireless
    - name: phpMyAdmin
      url: http://192.168.1.181/phpmyadmin
      icon: mdi:database
    - name: OctoPrint
      url: http://192.168.1.170:5000
      icon: mdi:printer-3d
    - name: Kodi Interface
      url: http://192.168.1.248:8080
      icon: mdi:kodi
    - name: Plex Interface
      url: http://plex.tv
      icon: mdi:plex
    

#
#
# FFMPEG Integration
#
ffmpeg:
  ffmpeg_bin: /usr/bin/ffmpeg

#
#
# Test of new YWeather Integration
#
weather:
  platform: yweather
  name: weather_today
  woeid: 2489882

