default_view:
  view: yes
  entities:
   - updater.updater
   - persistent_notification.invalid_config
#   - group.weather
   - group.forecast
   - group.avg_temps
   - group.perimiter
   - group.ecobee
   - group.people
   - group.alarm_system
   - group.traffic
   - group.events
   - camera.robert
   - group.nest_protect_downstairs
   - group.nest_protect_upstairs

cameras:
  name: Cameras
  view: yes
  entities:
   - camera.front_outside_house
   - camera.front_outside_house_alt
   - camera.front_of_house
   - camera.rear_of_house

rooms:
  name: Rooms
  view: yes
  entities:
   - group.outside
   - group.livingroom
   - group.hallway
   - group.office
   - group.bedroom
   - group.diningroom
   - group.tearoom
   - group.upstairs
   - group.ecobee
   - group.nest_protect_downstairs
   - group.nest_protect_upstairs

pws:
  name: Weather Station
  view: yes
  entities:
   - group.wunderground
   - group.pws_alerts
   - group.wxcameras
   - group.weather_statistics
   - group.forecast

media:
  name: Media Room
  view: yes
  entities:
   - group.mediaplayers
   - group.mediaswitches
   - group.plex_activity

system:
  name: System Status
  view: yes
  entities:
   - group.internet
   - group.wink_status
   - group.ha_status
   - group.system_status
   - group.local_devices

automation:
  name: Automation
  view: yes
  entities:
   - group.scenes
   - group.inputs
   - group.all_automations
   - group.all_scripts
   - group.weather

zwave:
  name: ZWave
  view: yes
  entities:
   - group.aeotec_lr_sensor
   - group.aeotec_br_sensor
   - group.aeotec_smart_switch_1
   - group.aeotec_smart_switch_2
   - group.aeotec_smart_energy_switch
   - group.garage


#
# Groups
#
weather:
  entities:
   - sensor.yr_symbol
   - sensor.dark_sky_condition
   - sensor.dark_sky_temperature
   - sensor.dark_sky_apparent_temperature
   - sensor.dark_sky_cloud_coverage
   - sensor.dark_sky_humidity
   - sensor.dark_sky_dew_point
   - sensor.dark_sky_precip
   - sensor.dark_sky_precip_type
   - sensor.dark_sky_precip_probability
   - sensor.dark_sky_precip_intensity
   - sensor.dark_sky_pressure
   - sensor.dark_sky_visibility
   - sensor.dark_sky_nearest_storm_distance
   - sensor.dark_sky_wind_bearing
   - sensor.dark_sky_wind_speed
forecast:
   - sensor.dark_sky_minutely_summary
   - sensor.dark_sky_hourly_summary
   - sensor.dark_sky_daily_summary
internet:
   - sensor.speedtest_ping
   - sensor.speedtest_download
   - sensor.speedtest_upload
   - sensor.update_speedtest
perimiter:
   - lock.front_door
   - light.front_door
   - light.side_door
   - light.garage
   - light.landscape
   - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
   - binary_sensor.mailbox
   - binary_sensor.aeotec_multisensor_6_sensor_7_0
   - binary_sensor.office_motion
   - binary_sensor.aeotec_multisensor_6_sensor_8_0
   - binary_sensor.tearoom_motion
   - binary_sensor.front_door
   - binary_sensor.kitchen_entry
   - binary_sensor.side_door
   - binary_sensor.tea_room_slider
   - binary_sensor.dining_room_1
   - binary_sensor.dining_room_2
   - binary_sensor.second_floor
bedroom:
   - binary_sensor.aeotec_multisensor_6_sensor_8_0
   - sensor.aeotec_multisensor_6_temperature_8_1
   - light.lightstrip1
   - light.bedroom_left
   - light.bedroom_right
tearoom:
   - binary_sensor.tearoom_motion
   - sensor.tearoom_temperature
   - light.tea_room_left
   - light.tea_room_right
   - switch.aeotec_smart_energy_switch_switch_9_0
diningroom:
   - light.dining_room
   - binary_sensor.tea_room_slider
   - binary_sensor.dining_room_1
   - binary_sensor.dining_room_2
livingroom:
   - binary_sensor.front_door
   - binary_sensor.aeotec_multisensor_6_sensor_7_0
   - sensor.aeotec_multisensor_6_temperature_7_1
   - light.sconces
   - light.lightstrip2
   - light.lightstrip3
   - light.lightstrip4
   - light.tv_light_l
   - light.tv_light_r
hallway:
   - switch.top_light_load
   - binary_sensor.main_floor_occupancy
office:
   - binary_sensor.office_motion
   - sensor.office_temperature
   - switch.office
upstairs:
   - binary_sensor.second_floor_motion
   - sensor.upstairs_temperature
   - sensor.second_floor_temperature
   - binary_sensor.upstairs_occupancy
garage:
   - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
   - light.garage
mediaplayers:
   - media_player.my_afts
   - media_player.my_afts_2
   - media_player.plex
   - media_player.office
   - media_player.living_room
   - media_player.bath
   - media_player.living_room_home
camera_group:
   - camera.front_outside_house
   - camera.front_outside_house_alt
   - camera.front_of_house
   - camera.rear_of_house
wxcameras:
   - camera.goes_east_sat
   - camera.ny_metro_wx_radar
   - camera.ny_metro_precip
ha_status:
   - sensor.current_ha_version
   - sensor.installed_version
   - sensor.since_last_boot
   - sensor.last_boot
   - sensor.cpu_use
   - sensor.memory_use_percent
   - sensor.ram_free
system_status:
   - sensor.rp1_disk_use
   - sensor.rp1_disk_use_2
   - sensor.rp1_disk_free
   - sensor.rp1_ram_use
   - sensor.rp1_ram_use_2
   - sensor.rp1_ram_free
   - sensor.rp1_swap_use_percent
   - sensor.rp1_swap_use
   - sensor.rp1_swap_use_2
   - sensor.rp1_swap_free
   - sensor.rp1_cpu_load
   - sensor.rp1_thread
   - sensor.rp1_total
   - sensor.rp1_running
   - sensor.rp1_sleeping
local_devices:
   - sensor.epsonprinter
   - sensor.brotherprinter
   - sensor.zen
   - sensor.satori
   - sensor.nirvana
   - sensor.acurite_wx
   - sensor.ex3700
people:
   - device_tracker.rpitera_rpitera
   - sensor.droid_battery
   - proximity.home
   - device_tracker.ford_fusion
   - sensor.fusion_fuel
   - binary_sensor.main_floor_occupancy
   - binary_sensor.upstairs_occupancy
wunderground:
   - sensor.pws_alerts
   - sensor.pws_weather
   - sensor.pws_station_id
   - sensor.pws_observation_time
   - sensor.pws_location
   - sensor.pws_elevation
   - sensor.pws_temp_f
   - sensor.pws_feelslike_f
   - sensor.pws_dewpoint_f
   - sensor.heat_index_f
   - sensor.pws_uv
   - sensor.pws_solarradiation
   - sensor.pws_visibility_mi
   - sensor.pws_relative_humidity
   - sensor.pws_pressure_in
   - sensor.pws_pressure_mb
   - sensor.pws_pressure_trend
   - sensor.pws_wind_degrees
   - sensor.pws_wind_dir
   - sensor.pws_wind_string
   - sensor.pws_wind_mph
   - sensor.pws_wind_gust_mph
   - sensor.pws_precip_1hr_in
   - sensor.pws_precip_today_in
   - sensor.pws_precip_today_string
nest_protect_downstairs:
   - binary_sensor.downstairs_nest_protect_online
   - sensor.downstairs_nest_protect_battery_health
   - sensor.downstairs_nest_protect_co_status
   - sensor.downstairs_nest_protect_smoke_status
#   - binary_sensor.home_downstairs_nest_protect_co_detected
#   - binary_sensor.home_downstairs_nest_protect_smoke_detected

nest_protect_upstairs:
   - binary_sensor.upstairs_nest_protect_online
   - sensor.upstairs_nest_protect_battery_health
   - sensor.upstairs_nest_protect_co_status
   - sensor.upstairs_nest_protect_smoke_status
#   - binary_sensor.home_upstairs_nest_protect_co_detected
#   - binary_sensor.home_upstairs_nest_protect_smoke_detected
alarm_system:
   - alarm_control_panel.ha_alarm
alarm_state:
   - light.front_door
   - binary_sensor.bedroom_motion
   - binary_sensor.kitchen_entry
   - binary_sensor.side_door
   - light.side_door
   - binary_sensor.tea_room_slider
   - binary_sensor.dining_room_1
   - binary_sensor.dining_room_2
   - binary_sensor.second_floor
traffic:
   - sensor.commute_travel_time
   - sensor.wilson_borough_travel_time
   - sensor.sandy_hook_travel_time
   - sensor.poconos_travel_time
scenes:
   - scene.tv_time
   - scene.sunset
   - scene.sunset_dimmed
   - scene.green_forest
   - scene.deep_blue
   - scene.landscape_colorloop
inputs:
   - input_boolean.sunup_switch
   - input_boolean.sundown_switch
   - input_boolean.mailbox_switch
   - sensor.washer_pwrdn
   - input_boolean.washer_switch
   - sensor.dryer_pwrup
   - input_boolean.dryer_switch
mediaswitches:
   - switch.watch_tv
   - switch.firetvplex
   - switch.chromecast
   - switch.bluray
aeotec_lr_sensor:
  name: Living Room
  entities:
   - binary_sensor.aeotec_multisensor_6_sensor_7_0
   - sensor.aeotec_multisensor_6_burglar_7_10
   - sensor.aeotec_multisensor_6_luminance_7_3
   - sensor.aeotec_multisensor_6_relative_humidity_7_5
   - sensor.aeotec_multisensor_6_temperature_7_1
aeotec_br_sensor:
  name: Bed Room
  entities:
   - binary_sensor.aeotec_multisensor_6_sensor_8_0
   - sensor.aeotec_multisensor_6_burglar_8_10
   - sensor.aeotec_multisensor_6_luminance_8_3
   - sensor.aeotec_multisensor_6_relative_humidity_8_5
   - sensor.aeotec_multisensor_6_temperature_8_1
aeotec_smart_energy_switch:
  name: Tea Room Fireplace
  entities:
   - switch.aeotec_smart_energy_switch_switch_9_0
   - sensor.aeotec_smart_energy_switch_voltage_9_15
   - sensor.aeotec_smart_energy_switch_power_9_4
   - sensor.aeotec_smart_energy_switch_previous_reading_9_1
aeotec_smart_switch_1:
  name: Washer
  entities:
   - switch.aeotec_smart_switch_6_switch_10_0
   - sensor.aeotec_smart_switch_6_voltage_10_16
   - sensor.aeotec_smart_switch_6_current_10_20
   - sensor.aeotec_smart_switch_6_power_10_8
   - sensor.aeotec_smart_switch_6_previous_reading_10_1
aeotec_smart_switch_2:
  name: Dryer
  entities:
   - switch.aeotec_smart_switch_6_switch_11_0
   - sensor.aeotec_smart_switch_6_voltage_11_16
   - sensor.aeotec_smart_switch_6_current_11_20
   - sensor.aeotec_smart_switch_6_power_11_8
   - sensor.aeotec_smart_switch_6_previous_reading_11_1
ecobee:
   - sensor.operating_mode
   - climate.main_floor
   - sensor.main_floor_humidity
   - sensor.main_floor_occupancy
   - sensor.main_floor_temperature
   - sensor.upstairs_occupancy
   - sensor.upstairs_temperature
outside:
   - light.front_door
   - light.side_door
   - light.garage
   - light.landscape
   - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
br_lights:
   - light.bedroom_left
   - light.bedroom_right
weather_statistics:
   - binary_sensor.temperature_up
   - binary_sensor.temperature_down
   - binary_sensor.pressure_up
   - binary_sensor.pressure_down
   - binary_sensor.humidity_up
   - binary_sensor.humidity_down
   - binary_sensor.wind_speed_up
   - binary_sensor.wind_speed_down
   - binary_sensor.precip_up
   - binary_sensor.precip_down
   - sensor.temperature_stats_mean
   - sensor.pws_wind_string
avg_temps:
  name: Average Home Temperature
  entities:
   - sensor.average_main_temp
   - sensor.average_upstairs_temp
wink_status:
  name: Wink System Status
  entities:
   - sensor.wink_core_api
   - sensor.wink_hub_api
   - sensor.winkcom
   - sensor.tcp_integration
   - sensor.echo_integration
plex_activity:
  name: Plex Activity Status
  entities:
   - sensor.nirvana_2
pws_alerts:
  name: Weather Warnings
  entities:
   - sensor.alert_description
   - sensor.alert_expires
   - sensor.alert_message
events:
  entities:
   - sensor.event_title
   - sensor.event_description
   - sensor.event_allday
   - sensor.event_start
   - sensor.event_end