default_view:
  view: true
  icon: mdi:home
  entities:
  - updater.updater
  - persistent_notification.invalid_config
  - weather.weather_today
  - group.perimiter
  - group.motion_sensors
  - group.laundry
  - group.presence
  - group.events
  - group.outdoor_lighting
  - group.avg_temps
  - group.alarm_system
  - group.almanac
  - group.traffic_info
  - camera.robert
  - group.ring
  - group.ecobee
  name: default_view
cameras:
  name: Cameras
  view: true
  entities:
  - group.interior_cams
  - group.exterior_cams
  - group.camera_presets
  - group.second_floor_cam_switches
rooms:
  name: Rooms
  view: true
  entities:
  - group.outside
  - group.livingroom
  - group.hallway
  - group.office
  - group.bedroom
  - group.diningroom
  - group.tearoom
  - group.upstairs
  - group.basement
  - group.ecobee
pws:
  name: Weather Station
  view: true
  entities:
  - group.wunderground
  - group.wxcameras
  - group.forecast4
  - group.aqi
  - group.weather_statistics
media:
  name: Media Room
  view: true
  entities:
  - group.mediaplayers
  - media_player.media_center
  - group.remote
  - group.plex_activity
  - group.internet_radio
system:
  name: System Status
  view: true
  entities:
  - group.links
  - group.internet
  - group.wink_devices
  - group.ha_status
  - group.system_status
  - group.local_devices
  - group.entity_epson25e37c
  - group.sensor_batteries
automation:
  name: Automation
  view: true
  entities:
  - group.scenes
  - group.inputs
  - group.all_automations
  - group.all_scripts
  - group.weather
3dprinter:
  name: Printer Lab
  view: true
  entities:
  - group.octoprint
  - camera.printercam
  - group.android_printercam
zwave:
  name: ZWave
  view: true
  entities:
  - group.aeotec_lr_sensor
  - group.aeotec_br_sensor
  - group.aeotec_smart_switch_1
  - group.aeotec_smart_switch_2
  - group.aeotec_smart_energy_switch
  - group.home_energy_meter
  - group.garage
  - group.zwave_devices
weather:
  name: weather
  entities:
  - sensor.dark_sky_summary
  - sensor.dark_sky_condition
  - sensor.dark_sky_temperature
  - sensor.dark_sky_dew_point
  - sensor.dark_sky_apparent_temperature
  - sensor.dark_sky_cloud_coverage
  - sensor.dark_sky_humidity
  - sensor.dark_sky_pressure
  - sensor.dark_sky_visibility
  - sensor.dark_sky_wind_bearing
  - sensor.dark_sky_wind_speed
  - sensor.dark_sky_precip_probability
  - sensor.dark_sky_precip
  - sensor.dark_sky_precip_type
  - sensor.dark_sky_precip_intensity
  - sensor.dark_sky_nearest_storm_distance
forecast:
  name: forecast
  entities:
  - sensor.pws_weather_1h
  - sensor.pws_weather_6h
  - sensor.pws_weather_1d
  - sensor.pws_weather_1n
  - sensor.pws_weather_2d
  - sensor.pws_weather_2n
forecast4:
  name: four day forecast
  entities:
  - sensor.pws_weather_1d
  - sensor.pws_weather_1n
  - sensor.pws_weather_2d
  - sensor.pws_weather_2n
  - sensor.pws_weather_3d
  - sensor.pws_weather_3n
  - sensor.pws_weather_4d
  - sensor.pws_weather_4n
  - sensor.pws_weather_5d
  - sensor.pws_weather_5n
internet:
  name: internet
  entities:
  - sensor.ssl_cert_expiration
  - sensor.speedtest_ping
  - sensor.speedtest_download
  - sensor.speedtest_upload
  - sensor.update_speedtest
outdoor_lighting:
  name: outdoor lighting
  entities:
  - light.front_light
  - light.side_light
  - light.garage
  - light.landscape
motion_sensors:
  name: motion detection
  entities:
  - binary_sensor.aeotec_multisensor_6_sensor_7_0
  - binary_sensor.aeotec_multisensor_6_sensor_8_0
  - binary_sensor.office_motion
  - binary_sensor.tearoom_motion
  - binary_sensor.second_floor_motion
  view: false
perimiter:
  name: perimiter
  entities:
  - lock.front_door
  - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
  - binary_sensor.mailbox_opened
  - group.doors
  - group.windows
bedroom:
  name: bedroom
  entities:
  - binary_sensor.aeotec_multisensor_6_sensor_8_0
  - sensor.aeotec_multisensor_6_temperature_8_1
  - light.lightstrip1
  - light.bedroom_left
  - light.bedroom_right
  - binary_sensor.brwl_opened
  - binary_sensor.brwr_opened
tearoom:
  name: tea room
  entities:
  - binary_sensor.tea_room_slider_opened
  - binary_sensor.tearoom_motion
  - sensor.tearoom_temperature
  - light.tea_room_left
  - light.tea_room_right
diningroom:
  name: dining room
  entities:
  - light.dining_room
  - binary_sensor.drwl_sensor_14_0
  - binary_sensor.drwr_sensor_15_0
livingroom:
  name: living room
  entities:
  - binary_sensor.front_entry_opened
  - binary_sensor.aeotec_multisensor_6_sensor_7_0
  - sensor.aeotec_multisensor_6_temperature_7_1
  - switch.outlet_1
  - switch.outlet_2
  - light.sconces
  - light.lightstrip2
  - light.lightstrip3
  - light.lightstrip4
  - light.uplight_left
  - light.uplight_right
hallway:
  name: hallway
  entities:
  - switch.hallway
  - binary_sensor.main_floor_occupancy
  - group.nest_protect_downstairs
office:
  name: office
  entities:
  - binary_sensor.office_motion
  - sensor.office_temperature
  - switch.aeotec_smart_energy_switch_switch_9_0
  - switch.wall_unit
  - light.office_lightstrip
upstairs:
  name: second floor
  entities:
  - binary_sensor.second_floor_motion
  - binary_sensor.upstairs_occupancy
  - binary_sensor.upstairs_bathroom_liquid_detected
  - sensor.upstairs_temperature
  - group.nest_protect_upstairs
basement:
  name: basement
  entities:
  - switch.valve
  - binary_sensor.laundry_room_liquid_detected
garage:
  name: garage
  entities:
  - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
  - light.garage
mediaplayers:
  name: mediaplayers
  entities:
  - media_player.bath
  - media_player.bedroom
  - media_player.kodi
  - media_player.living_room_home
  - media_player.living_room_tv
  - media_player.office
  - media_player.shield
  - media_player.shield_2
  - media_player.shield_3
camera_group:
  name: camera group
  entities:
  - camera.front_outside_house
  - camera.front_outside_house_alt
  - camera.front_of_house
  - camera.rear_of_house
wxcameras:
  name: wxcameras
  entities:
  - camera.goes_east_sat
  - camera.ny_metro_wx_radar
  - camera.ny_metro_precip
  - camera.northeast_lightning_strikes
ha_status:
  name: ha status
  entities:
  - sensor.current_ha_version
  - sensor.installed_version
  - input_select.log_level
system_status:
  name: system status
  entities:
  - sensor.rp1_disk_use
  - sensor.rp1_disk_use_2
  - sensor.rp1_disk_free
  - sensor.rp1_ram_use
  - sensor.rp1_ram_use_2
  - sensor.rp1_ram_free
  - sensor.rp1_swap_use_percent
  - sensor.rp1_swap_use
  - sensor.rp1_swap_use_2
  - sensor.rp1_swap_free
  - sensor.rp1_cpu_load
  - sensor.rp1_thread
  - sensor.rp1_total
  - sensor.rp1_running
  - sensor.rp1_sleeping
  - sensor.since_last_boot
  - sensor.last_boot
  - sensor.cpu_use
  - sensor.memory_use_percent
  - sensor.ram_free
local_devices:
  name: local devices
  entities:
  - sensor.epsonprinter
  - sensor.brotherprinter
  - sensor.zen
  - sensor.satori
  - sensor.nirvana
  - sensor.acurite_wx
  - sensor.ex3700
presence:
  name: presence
  entities:
  - device_tracker.rpitera_rpitera
  - sensor.droid_battery
  - proximity.home
  - device_tracker.ford_fusion
  - sensor.fusion_fuel
  - binary_sensor.main_floor_occupancy
  - binary_sensor.upstairs_occupancy
wunderground:
  name: wunderground
  entities:
  - sensor.pws_alerts
  - sensor.pws_weather
  - sensor.pws_station_id
  - sensor.pws_observation_time
  - sensor.pws_location
  - sensor.pws_elevation
  - sensor.pws_temp_f
  - sensor.pws_feelslike_f
  - sensor.pws_dewpoint_f
  - sensor.heat_index_f
  - sensor.pws_uv
  - sensor.pws_solarradiation
  - sensor.pws_visibility_mi
  - sensor.pws_relative_humidity
  - sensor.pws_pressure_in
  - sensor.pws_pressure_mb
  - sensor.pws_pressure_trend
  - sensor.pws_wind_degrees
  - sensor.pws_wind_dir
  - sensor.pws_wind_string
  - sensor.pws_wind_mph
  - sensor.pws_wind_gust_mph
  - sensor.pws_precip_1hr_in
  - sensor.pws_precip_today_in
  - sensor.pws_precip_today_string
nest_protect_downstairs:
  name: nest protect main floor
  entities:
  - binary_sensor.downstairs_nest_protect_online
  - sensor.downstairs_nest_protect_battery_health
  - sensor.downstairs_nest_protect_co_status
  - sensor.downstairs_nest_protect_smoke_status
nest_protect_upstairs:
  name: nest protect second floor
  entities:
  - binary_sensor.upstairs_nest_protect_online
  - sensor.upstairs_nest_protect_battery_health
  - sensor.upstairs_nest_protect_co_status
  - sensor.upstairs_nest_protect_smoke_status
alarm_system:
  name: alarm system
  entities:
  - alarm_control_panel.ha_alarm
alarm_state:
  name: alarm state
  entities:
  - binary_sensor.aeotec_multisensor_6_sensor_7_0
  - binary_sensor.aeotec_multisensor_6_sensor_8_0
  - binary_sensor.office_motion
  - binary_sensor.tearoom_motion
  - binary_sensor.second_floor_motion
  - binary_sensor.kitchen_entry_opened
  - binary_sensor.side_entry_opened
  - binary_sensor.front_entry_opened
  - binary_sensor.tea_room_slider_opened
  - binary_sensor.dining_room_1_opened
  - binary_sensor.dining_room_2_opened
traffic_info:
  name: traffic info
  entities:
  - sensor.ewr_travel_time
  - sensor.westfield_travel_time
  - sensor.garwood_travel_time
  - sensor.bound_brook_travel_time
  - sensor.bridgewater_area_travel_time
  - sensor.wilson_borough_travel_time
  - sensor.sandy_hook_travel_time
  - sensor.poconos_travel_time
scenes:
  name: scenes
  entities:
  - scene.sunset
  - scene.sunset_dimmed
  - scene.green_forest
  - scene.deep_blue
inputs:
  name: inputs
  entities:
  - input_boolean.sunup_switch
  - input_boolean.sundown_switch
  - input_boolean.mailbox_switch
  - sensor.washer_pwrup
  - input_boolean.washer_switch
  - sensor.dryer_pwrup
  - input_boolean.dryer_switch
remote:
  name: remotes
  entities:
  - remote.living_room
  - sensor.current_activity
  - input_select.living_room_tv
  - remote.bedroom
  - sensor.current_activity_br
  - input_select.bedroom_tv
aeotec_lr_sensor:
  name: living room
  entities:
  - binary_sensor.aeotec_multisensor_6_sensor_7_0
  - sensor.aeotec_multisensor_6_burglar_7_10
  - sensor.aeotec_multisensor_6_luminance_7_3
  - sensor.aeotec_multisensor_6_relative_humidity_7_5
  - sensor.aeotec_multisensor_6_temperature_7_1
aeotec_br_sensor:
  name: bedroom
  entities:
  - binary_sensor.aeotec_multisensor_6_sensor_8_0
  - sensor.aeotec_multisensor_6_burglar_8_10
  - sensor.aeotec_multisensor_6_luminance_8_3
  - sensor.aeotec_multisensor_6_relative_humidity_8_5
  - sensor.aeotec_multisensor_6_temperature_8_1
aeotec_smart_energy_switch:
  name: office a/c
  entities:
  - switch.aeotec_smart_energy_switch_switch_9_0
  - sensor.aeotec_smart_energy_switch_voltage_9_15
  - sensor.aeotec_smart_energy_switch_power_9_4
  - sensor.aeotec_smart_energy_switch_previous_reading_9_1
  view: false
aeotec_smart_switch_1:
  name: washer
  entities:
  - switch.aeotec_smart_switch_6_switch_10_0
  - sensor.aeotec_smart_switch_6_voltage_10_16
  - sensor.aeotec_smart_switch_6_current_10_20
  - sensor.aeotec_smart_switch_6_power_10_8
  - sensor.aeotec_smart_switch_6_previous_reading_10_1
aeotec_smart_switch_2:
  name: dryer
  entities:
  - switch.aeotec_smart_switch_6_switch_11_0
  - sensor.aeotec_smart_switch_6_voltage_11_16
  - sensor.aeotec_smart_switch_6_current_11_20
  - sensor.aeotec_smart_switch_6_power_11_8
  - sensor.aeotec_smart_switch_6_previous_reading_11_1
ecobee:
  name: ecobee
  entities:
  - sensor.operating_mode
  - script.ecobee_resume
  - climate.main_floor
  - sensor.main_floor_humidity
  - sensor.main_floor_occupancy
  - sensor.main_floor_temperature
  - sensor.upstairs_occupancy
  - sensor.upstairs_temperature
outside:
  name: outside
  entities:
  - light.front_light
  - light.side_light
  - light.garage
  - light.landscape
  - binary_sensor.mailbox_opened
  - binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
br_lights:
  name: br lights
  entities:
  - light.bedroom_left
  - light.bedroom_right
weather_statistics:
  name: weather statistics
  entities:
  - binary_sensor.temperature_up
  - binary_sensor.temperature_down
  - binary_sensor.pressure_up
  - binary_sensor.pressure_down
  - binary_sensor.humidity_up
  - binary_sensor.humidity_down
  - binary_sensor.wind_speed_up
  - binary_sensor.wind_speed_down
  - binary_sensor.precip_up
  - binary_sensor.precip_down
  - sensor.temperature_stats_mean
  - sensor.pws_wind_string
avg_temps:
  name: environmental
  entities:
  - sensor.average_main_temp
  - sensor.average_upstairs_temp
plex_activity:
  name: plex activity status
  entities:
  - sensor.nirvana_2
events:
  name: events
  entities:
  - sensor.event_title
  - sensor.event_description
  - sensor.event_start
  - sensor.event_end
  - sensor.event_allday
  view: false
laundry:
  name: laundry
  entities:
  - sensor.washer_pwrup
  - sensor.dryer_pwrup
interior_cams:
  name: interior cams
  entities:
  - camera.interior_street_facing_controllable
  - camera.rear_facing_controllable
  - camera.interior_bedroom_fixed
exterior_cams:
  name: exterior cams
  entities:
  - camera.outside_front_left_fixed
  - camera.outside_front_right_fixed
  - camera.second_floor
wink_devices:
  name: wink devices
  entities:
  - binary_sensor.main_hub
  - binary_sensor.wink_relay
  - binary_sensor.philips_hue
almanac:
  name: almanac
  entities:
  - sun.sun
  - sensor.nextsunrise
  - sensor.nextsunset
  - sensor.moon
  - sensor.dayofyear
  - sensor.weekofyear
aqi:
  name: air quality index
  entities:
  - sensor.waqi_rahway_pm_newjersey_usa
  - sensor.dark_sky_ozone
camera_presets:
  name: camera presets
  entities:
  - script.f_ir_off
  - input_select.camera1
  - input_select.camera2
ring:
  name: ring doorbell
  entities:
  - binary_sensor.ring_doorbell_ding
  - sensor.ring_last_ding
  - binary_sensor.ring_doorbell_motion
  - sensor.ring_last_motion
  - sensor.ring_doorbell_volume
  - sensor.ring_doorbell_battery
  - sensor.ring_first_floor_volume
internet_radio:
  name: internet radio
  entities:
  - input_select.radio_station
  - input_select.chromecast_radio
  - script.radio538
  - input_slider.volume_radio
links:
  name: management interfaces
  entities:
  - weblink.webmin
  - weblink.router
  - weblink.phpmyadmin
  - weblink.octoprint
  - weblink.kodi_interface
  - weblink.plex_interface
night_switches:
  name: night switch group
  entities:
  - switch.wall_unit
  - switch.outlet_2
  - switch.outlet_1
  - switch.aeotec_smart_energy_switch_switch_9_0
zwave_devices:
  name: zwave device status
  entities:
  - zwave.aeotec_zstick_gen5_1
  - zwave.aeotec_multisensor_6_7
  - zwave.aeotec_multisensor_6_8
  - zwave.aeotec_smart_energy_switch_9
  - zwave.aeotec_smart_switch_6_10
  - zwave.aeotec_smart_switch_6_11
  - zwave.vision_zg8101_garage_door_detector_12
  - zwave.aeotec_dsb09104_home_energy_meter_13
  - zwave.drwl_14
  - zwave.drwr_15
  - zwave.stairsw_16
android_printercam:
  name: android printercam controls
  entities:
  - sensor.printercam_audio_connections
  - sensor.printercam_battery_level
  - sensor.printercam_ambient_temp
  - sensor.printercam_battery_voltage
  - sensor.printercam_light_level
  - sensor.printercam_motion
  - sensor.printercam_pressure
  - sensor.webcam_pressure_inches
  - group.android_printercam_switches
android_printercam_switches:
  entities:
  - switch.printercam_exposure_lock
  - switch.printercam_focus
  - switch.printercam_frontfacing_camera
  - switch.printercam_gps_active
  - switch.printercam_night_vision
  - switch.printercam_overlay
  - switch.printercam_torch
  - switch.printercam_video_recording
  - switch.printercam_white_balance_lock
second_floor_cam_switches:
  name: second floor cam controls
  entities:
  - switch.second_floor_exposure_lock
  - switch.second_floor_focus
  - switch.second_floor_night_vision
  - switch.second_floor_overlay
  - switch.second_floor_video_recording
  - switch.second_floor_white_balance_lock
octoprint:
  entities:
  - binary_sensor.octoprint_printing
  - binary_sensor.octoprint_printing_error
  - sensor.bed
  - sensor.hotend
  - sensor.octoprint_current_state
  - sensor.octoprint_job_percentage
  - sensor.bed_target
  - sensor.hotend_target
entity_epson25e37c:
  name: epson ink status
  entities:
  - input_slider.epson25e37c_cyan
  - input_slider.epson25e37c_magenta
  - input_slider.epson25e37c_yellow
  - input_slider.epson25e37c_black
sensor_batteries:
  name: sensor battery levels
  entities:
  - sensor.front_entry_battery
  - sensor.kitchen_entry_battery
  - sensor.side_entry_battery
  - sensor.tea_room_slider_battery
  - sensor.dining_room_1_battery
  - sensor.dining_room_2_battery
  - sensor.mailbox_battery
  - sensor.office_motion_battery
  - sensor.tearoom_motion_battery
  - sensor.second_floor_motion_battery
  - sensor.siren_battery
  - sensor.garagedoor_battery
  - sensor.ring_doorbell_battery
home_energy_meter:
  name: home energy meter
  entities:
  - zwave.aeotec_dsb09104_home_energy_meter_13
  - sensor.aeotec_dsb09104_home_energy_meter_power_13_4
  - sensor.aeotec_dsb09104_home_energy_meter_energy_13_0
  - sensor.aeotec_dsb09104_home_energy_meter_previous_reading_13_1
  - sensor.aeotec_dsb09104_home_energy_meter_interval_13_2
  
  
windows:
  name: Windows
  entities:
  - binary_sensor.brwl_opened
  - binary_sensor.brwr_opened
  - binary_sensor.drwl_sensor_14_0
  - binary_sensor.drwr_sensor_15_0
  - binary_sensor.stairsw_sensor_16_0
doors:
  name: Doors
  entities:
  - binary_sensor.front_entry_opened
  - binary_sensor.kitchen_entry_opened
  - binary_sensor.side_entry_opened
  - binary_sensor.tea_room_slider_opened
