- platform: mqtt
  name: "Watch TV"
  state_topic:   "harmony-api/activities/watch-tv/state"
  command_topic: "harmony-api/activities/watch-tv/command"
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "FireTV/Plex"
  state_topic:   "harmony-api/activities/watch-fire-tv/state"
  command_topic: "harmony-api/activities/watch-fire-tv/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "Chromecast"
  state_topic:   "harmony-api/activities/chromecast/state"
  command_topic: "harmony-api/activities/chromecast/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"
- platform: mqtt
  name: "BluRay"
  state_topic:   "harmony-api/activities/watch-a-dvd/state"
  command_topic: "harmony-api/activities/watch-a-dvd/command"
  qos: 0
  payload_on: "on"
  payload_off: "off"