binary_sensor.aeotec_multisensor_6_sensor_7_0:
  ignored: false
  polling_intensity: 1
binary_sensor.aeotec_multisensor_6_sensor_8_0:
  ignored: false
  polling_intensity: 1
zwave.aeotec_home_energy_meter_13:
  ignored: false
  polling_intensity: 1
zwave.aeotec_dsb09104_home_energy_meter_13:
  ignored: false
  polling_intensity: 1
