#
# Media Players
#


- platform: plex
  include_non_clients: true
  use_episode_art: true
  use_dynamic_groups: true
  scan_interval: 15

- platform: cast

- platform: firetv

- platform: kodi
  host: 192.168.1.248
  enable_websocket: true
  

- platform: universal
  name: Media Center
  children:
    - media_player.bath
    - media_player.bde5900_bde5900
    - media_player.bedroom
    - media_player.home_group
    - media_player.kodi
    - media_player.living_room_home
    - media_player.living_room_tv
    - media_player.office
    - media_player.shield
    - media_player.shield_2
    - media_player.shield_3
  
