#Arm alarm in home mode
- alias: 'Armed home'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_entry_opened
      state: 'on'
    - platform: state
      entity_id: binary_sensor.side_door_opened
      state: 'on'
    - platform: state
      entity_id: binary_sensor.second_floor_motion
      state: 'on'
    - platform: state
      entity_id: binary_sensor.tearoom_motion
      state: 'on'
    - platform: state
      entity_id: binary_sensor.office_motion
      state: 'on'
    - platform: state
      entity_id: binary_sensor.tea_room_slider_opened
    - platform: state
      entity_id: binary_sensor.dining_room_1_opened
      state: 'on'
    - platform: state
      entity_id: binary_sensor.dining_room_2_opened
      state: 'on'
    - platform: state
      entity_id: binary_sensor.tea_room_slider_opened
      state: 'on'
  condition:
    condition: state
    entity_id: alarm_control_panel.ha_alarm
    state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.pushbullet
      data:
        message: 'Robert, the alarm has been triggered.'