# Dryer Notification Sequence Done
- alias: 'Dryer Done - away'
  trigger:
    platform: state
    entity_id: sensor.aeotec_smart_switch_6_power_11_8
    state: '0.0'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.dryer_switch
        state: 'on'
      - condition: state
        entity_id: device_tracker.rpitera_rpitera
        state: 'not_home'
  action:
    - service: notify.pushbullet
      data:
        message: 'Robert, the dryer is done.'
    - service: input_boolean.turn_off
      entity_id: input_boolean.dryer_switch