- alias: "Keep Dryer Powered On"
  trigger:
    platform: state
    entity_id: switch.aeotec_smart_switch_6_switch_11_0
    from: 'on'
    to: 'off'
  action:
    - service: notify.pushbullet
      data_template:
        message: 'Dryer was switched off, turning back on'
    - service: switch.turn_on
      entity_id: switch.aeotec_smart_switch_6_switch_11_0