# Garage Door Light
- alias: 'Garage Light'
  trigger:
    platform: state
    entity_id: binary_sensor.vision_zg8101_garage_door_detector_sensor_12_0
    state: 'on'
  condition:
    condition: sun
    after: sunset
    after_offset: "-01:00:00"
  action:
    - service: light.turn_on
      entity_id: light.garage
    - delay: 00:02:30
    - service: light.turn_off
      entity_id: light.garage