# Turn on Spirit's light just before sunset - updated 7/18/17
- alias: 'Kitty Light On'
  trigger:
    platform: sun
    event: sunset
    offset: '-00:45:00'
  action:
    service: light.turn_on
    data_template:
      entity_id: light.dining_room
      