# Turn on Spirit's light after sunset and then turn off at 11:00 PM
- alias: 'Kitty Light On'
  trigger:
    platform: sun
    event: sunset
  action:
    service: light.turn_on
    data_template:
      entity_id: light.dining_room
      