# Turn on Spirit's light just before sunset and then turn off at 11:00 PM
- alias: 'Kitty Light Off'
  trigger:
    platform: time
    at: '23:00'
  action:
    service: light.turn_off
    data_template:
      entity_id: light.dining_room
      