# Notify when Mail has arrived - Home
- alias: 'Mail Alert Home'
  trigger:
    platform: state
    entity_id: binary_sensor.mailbox_opened
    from: 'off'
  condition:
    condition: and
    conditions:
      - condition: state
        entity_id: input_boolean.mailbox_switch
        state: 'off'
      - condition: state
        entity_id: device_tracker.rpitera_rpitera
        state: 'home'
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data:
        message: 'Pardon the interruption, Robert but the mail has been delivered.'
    - service: input_boolean.turn_on
      entity_id: input_boolean.mailbox_switch