- alias: "Listen to Music started from HASS"
  trigger:
    platform: state
    entity_id: input_select.living_room_tv
    to: 'Listen to Music'
  action:
    service: script.turn_on
    entity_id: script.music