- alias: "Music started from Harmony Hub"
  trigger:
    platform: state
    entity_id: remote.living_room
  condition:
    condition: template
    value_template: '{{ trigger.to_state.attributes.current_activity == "Listen to Music" }}'
  action:
    service: input_select.select_option
    entity_id: input_select.living_room_tv
    data:
      option: "Listen to Music"