# Notify when Octoprint Job has printed - Home
- alias: 'OctoPrint Alert Home'
  trigger:
    platform: state
    entity_id: sensor.octoprint_current_state
    from: 'Printing'
    to: 'Operational'
  condition:
    condition: state
    entity_id: device_tracker.rpitera_rpitera
    state: 'home'
  action:
    service: tts.google_say
    entity_id: media_player.living_room_home
    data:
      message: 'Congratulations, Robert! You have hacked matter. Your build has completed.'
    