# Precip Alert - Home version
- alias: 'Precip Alert'
  trigger:
    platform: numeric_state
    entity_id: sensor.dark_sky_precip_probability
    above: '65'
  condition:
    condition: time
    after: '8:00:00'
    before: '23:00:00'
  action:
    - service: tts.google_say
      entity_id: media_player.living_room_home
      data_template:
        message: 'Excuse me Robert, but precipitation is expected. Probability is {{ states.sensor.dark_sky_precip_probability.state | int }}percent.  Forecast says {{ states.sensor.pws_weather_1h.state }} for the next hour.'
        cache: false
    - service: automation.turn_off
      entity_id: automation.raining
    - delay: 00:30:00
    - service: automation.turn_on
      entity_id: automation.raining
