- alias: 'Set Radio Volume'
  trigger:
    platform: state
    entity_id: input_slider.volume_radio
  action:
    service: media_player.volume_set
    data_template:
      entity_id: >
        {% if is_state("input_select.chromecast_radio", "Living Room") %} media_player.living_room_tv
        {% elif is_state("input_select.chromecast_radio", "Bedroom") %} media_player.bedroom
        {% elif is_state("input_select.chromecast_radio", "Bath") %} media_player.bath
        {% elif is_state("input_select.chromecast_radio", "Office") %} media_player.office
        {% elif is_state("input_select.chromecast_radio", "Multi-Room") %} media_player.home_group
        {% endif %}
      volume_level: '{{  states.input_slider.volume_radio.state  }}'