- alias: "Watch Bedroom TV started from HASS"
  trigger:
    platform: state
    entity_id: input_select.bedroom_tv
    to: 'Watch TV'
  action:
    service: script.turn_on
    entity_id: script.watch_tv_br