- alias: 'Send notification when sun sets'
  trigger:
    platform: sun
    event: sunset
    offset: '+00:00:00'
  action:
    service: notify.pushbullet
    data:
      message: 'The sun has set Robert. Have a good evening.'

