- alias: 'Send notification when sun rises'
  trigger:
    platform: sun
    event: sunrise
    offset: '+00:00:00'
  action:
    service: notify.pushbullet
    data:
      message: 'The sun is up Robert. Hope you have a good day'