- alias: 'Trigger alarm while armed home'
  trigger:
    - platform: state
      entity_id: binary_sensor.kitchen_entry
      state: 'on'
    - platform: state
      entity_id: binary_sensor.side_door
      state: 'on'
    - platform: state
      entity_id: binary_sensor.second_floor
      state: 'on'
    - platform: state
      entity_id: binary_sensor.tea_room_slider
      state: 'on'
    - platform: state
      entity_id: binary_sensor.dining_room_1
      state: 'on'
    - platform: state
      entity_id: binary_sensor.dining_room_2
      state: 'on'
    - platform: state
      entity_id: binary_sensor.tea_room_slider
      state: 'on'
  condition:
    - platform: state
      entity_id: alarm_control_panel.ha_alarm
      state: armed_home
  action:
    - service: alarm_control_panel.alarm_trigger
      entity_id: alarm_control_panel.ha_alarm
    - service: notify.pushbullet
      data:
        message: 'The alarm has been triggered.'
